module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'api-gateway',
        'auth-service',
        'notification-service',
        'analytics-service',
        'types',
        'config',
        'logger',
        'auth',
        'authz',
        'database',
        'nest-common',
        'infra',
        'ci',
        'docs',
        'web',
        'website',
        'deps',
        'repo',
        'e2e',
        'events',
        'audit',
        'workflow-service',
        'document-service',
        'gcc-service',
        'ai-service',
      ],
    ],
  },
};
